### ISSUE TITLE
Переход на другой контекст

### ISSUE THREAD

**Issue by lelvisl** [lelvisl/couchbase_exporter#2]
Уже есть официальный пакет контекста, отвязанный от net

https://golang.org/pkg/context/

https://github.com/lelvisl/couchbase_exporter/blob/d7cf45d5dfa2cceb5db8814b86a5377624d1b0ea/couchbase_exporter.go#L10
https://github.com/lelvisl/couchbase_exporter/blob/d7cf45d5dfa2cceb5db8814b86a5377624d1b0ea/couchbase_exporter.go#L62

**Comment by SergeyParamoshkin** [comment]
done
